import tkinter as tk
import tkinter

window = tk.Tk()
window.configure(background='aliceblue')
window.title("Machine Simulator")

# setting layout of main window
window.grid_columnconfigure(2,weight=1)
window.grid_rowconfigure(3,weight=1)

# creating the register frame and place it
registersGPRFrame = tk.Frame(window)
registersGPRFrame.grid(column=0,row=0) 
registersGPRFrame.grid_columnconfigure(1, weight=1, minsize=50)
registersGPRFrame.grid_columnconfigure(4, weight=1, minsize=50)

# creating labels for 4 general purpose registers 
btn1 = tk.Label(registersGPRFrame, text = "GPR 0", fg = "green",padx=5,pady=5,relief=tk.RAISED)
btn1.grid(row=0,column=0)
gpr0_1 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=1)
gpr0_2 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=2)
gpr0_3 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=3)
gpr0_4 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=4)
gpr0_5 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=5)
gpr0_6 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=6)
gpr0_7 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=7)
gpr0_8 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=8)
gpr0_9 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=9)
gpr0_10 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=10)
gpr0_11 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=11)
gpr0_12 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=12)
gpr0_13 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=13)
gpr0_14 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=14)
gpr0_15 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=15)
gpr0_16 = tk.Checkbutton(registersGPRFrame, text='').grid(row=0,column=16)
gpr0_LD = tk.Button(registersGPRFrame, text = "LD", fg = "green",padx=5,pady=5,relief=tk.RAISED).grid(row=0,column=17)

btn2 = tk.Label(registersGPRFrame, text = "GPR 1", fg = "green",padx=5,pady=5,relief=tk.RAISED)
btn2.grid(row=1,column=0)
gpr1_1 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=1)
gpr1_2 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=2)
gpr1_3 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=3)
gpr1_4 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=4)
gpr1_5 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=5)
gpr1_6 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=6)
gpr1_7 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=7)
gpr1_8 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=8)
gpr1_9 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=9)
gpr1_11 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=10)
gpr1_11 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=11)
gpr1_12 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=12)
gpr1_13 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=13)
gpr1_14 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=14)
gpr1_15 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=15)
gpr1_16 = tk.Checkbutton(registersGPRFrame, text='').grid(row=1,column=16)
gpr1_LD = tk.Button(registersGPRFrame, text = "LD", fg = "green",padx=5,pady=5,relief=tk.RAISED).grid(row=1,column=17)

btn3 = tk.Label(registersGPRFrame, text = "GPR 2", fg = "green",padx=5,pady=5,relief=tk.RAISED)
btn3.grid(row=2,column=0)
gpr2_1 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=1)
gpr2_2 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=2)
gpr2_3 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=3)
gpr2_4 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=4)
gpr2_5 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=5)
gpr2_6 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=6)
gpr2_7 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=7)
gpr2_8 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=8)
gpr2_9 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=9)
gpr2_11 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=10)
gpr2_11 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=11)
gpr2_12 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=12)
gpr2_13 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=13)
gpr2_14 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=14)
gpr2_15 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=15)
gpr2_16 = tk.Checkbutton(registersGPRFrame, text='').grid(row=2,column=16)
gpr2_LD = tk.Button(registersGPRFrame, text = "LD", fg = "green",padx=5,pady=5,relief=tk.RAISED).grid(row=2,column=17)

btn4 = tk.Label(registersGPRFrame, text = "GPR 3", fg = "green",padx=5,pady=5,relief=tk.RAISED)
btn4.grid(row=3,column=0)
gpr3_1 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=1)
gpr3_3 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=2)
gpr3_3 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=3)
gpr3_4 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=4)
gpr3_5 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=5)
gpr3_6 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=6)
gpr3_7 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=7)
gpr3_8 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=8)
gpr3_9 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=9)
gpr3_11 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=10)
gpr3_11 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=11)
gpr3_13 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=12)
gpr3_13 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=13)
gpr3_14 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=14)
gpr3_15 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=15)
gpr3_16 = tk.Checkbutton(registersGPRFrame, text='').grid(row=3,column=16)
gpr3_LD = tk.Button(registersGPRFrame, text = "LD", fg = "green",padx=5,pady=5,relief=tk.RAISED).grid(row=3,column=17)


# creating the register frame and place it
indexFrame = tk.Frame(window)
indexFrame.grid(row=2,column=0)
indexFrame.grid_columnconfigure(1, weight=1, minsize=50)
indexFrame.grid_columnconfigure(4, weight=1, minsize=50)

#labels for  3 Index Registers 1-3
btn5 = tk.Label(indexFrame , text = "IXR 1", fg = "blue",padx=5,pady=5,relief=tk.RAISED)
btn5.grid(row=5,column=0)
ixr1_1 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=1)
ixr1_2 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=2)
ixr1_3 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=3)
ixr1_4 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=4)
ixr1_5 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=5)
ixr1_6 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=6)
ixr1_7 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=7)
ixr1_8 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=8)
ixr1_9 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=9)
ixr1_10 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=10)
ixr1_11 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=11)
ixr1_12 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=12)
ixr1_13 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=13)
ixr1_14 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=14)
ixr1_15 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=15)
ixr1_16 = tk.Checkbutton(indexFrame, text='').grid(row=5,column=16)
ixr1_LD = tk.Button(indexFrame, text = "LD", fg = "green",padx=5,pady=5,relief=tk.RAISED).grid(row=5,column=17)

btn6 = tk.Label(indexFrame , text = "IXR 2", fg = "blue",padx=5,pady=5,relief=tk.RAISED)
btn6.grid(row=6,column=0)
ixr2_1 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=1)
ixr2_2 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=2)
ixr2_3 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=3)
ixr2_4 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=4)
ixr2_5 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=5)
ixr2_6 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=6)
ixr2_7 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=7)
ixr2_8 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=8)
ixr2_9 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=9)
ixr2_10 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=10)
ixr2_11 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=11)
ixr2_12 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=12)
ixr2_13 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=13)
ixr2_14 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=14)
ixr2_15 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=15)
ixr2_16 = tk.Checkbutton(indexFrame, text='').grid(row=6,column=16)
ixr2_LD = tk.Button(indexFrame, text = "LD", fg = "green",padx=5,pady=5,relief=tk.RAISED).grid(row=6,column=17)

btn7 = tk.Label(indexFrame , text = "IXR 3", fg = "blue",padx=5,pady=5,relief=tk.RAISED)
btn7.grid(row=7,column=0)
ixr3_1 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=1)
ixr3_2 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=2)
ixr3_3 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=3)
ixr3_4 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=4)
ixr3_5 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=5)
ixr3_6 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=6)
ixr3_7 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=7)
ixr3_8 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=8)
ixr3_9 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=9)
ixr3_10 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=10)
ixr3_11 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=11)
ixr3_12 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=12)
ixr3_13 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=13)
ixr3_14 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=14)
ixr3_15 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=15)
ixr3_16 = tk.Checkbutton(indexFrame, text='').grid(row=7,column=16)
ixr3_LD = tk.Button(indexFrame, text = "LD", fg = "green",padx=5,pady=5,relief=tk.RAISED).grid(row=7,column=17)

# creating frame for PC, MAR, MBR, IR, MFR, Privileged 
otherFrame = tk.Frame(window)
otherFrame.grid(row=0,column=2)
otherFrame.grid_columnconfigure(4, weight=1, minsize=50)

# labelfor for PC, MAR, MBR, IR, MFR, Privileged
btn8 = tk.Label(otherFrame, text = "PC", fg = "blue",width=6,relief=tk.RAISED,justify='right')
btn8.grid(row=1,column=22)
pc_1 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=23)
pc_2 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=24)
pc_3 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=25)
pc_4 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=26)
pc_5 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=27)
pc_6 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=28)
pc_7 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=29)
pc_8 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=30)
pc_9 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=31)
pc_10 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=32)
pc_11 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=33)
pc_12 = tk.Checkbutton(otherFrame, text='').grid(row=1,column=34)
pc_LD7= tk.Button(otherFrame, text = "LD", fg = "green",padx=5,pady=5,relief=tk.RAISED).grid(row=1,column=35)

btn9 = tk.Label(otherFrame, text = "MAR", fg = "blue",padx=5,pady=5,relief=tk.RAISED)
btn9.grid(row=2,column=22)
mar_1 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=23)
mar_2 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=24)
mar_3 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=25)
mar_4 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=26)
mar_5 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=27)
mar_6 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=28)
mar_7 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=29)
mar_8 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=30)
mar_9 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=31)
mar_10 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=32)
mar_11 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=33)
mar_12 = tk.Checkbutton(otherFrame, text='').grid(row=2,column=34)
mar_LD = tk.Button(otherFrame, text = "LD", fg = "green",padx=5,pady=5,relief=tk.RAISED).grid(row=2,column=35)

btn10 = tk.Label(otherFrame, text = "MBR", fg = "blue",padx=5,pady=5,relief=tk.RAISED)
btn10.grid(row=3,column=18)
mbr_1 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=19)
mbr_2 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=20)
mbr_3 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=21)
mbr_4 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=22)
mbr_5 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=23)
mbr_6 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=24)
mbr_7 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=25)
mbr_8 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=26)
mbr_9 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=27)
mbr_10 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=28)
mbr_11 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=29)
mbr_12 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=30)
mbr_13 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=31)
mbr_14 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=32)
mbr_15 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=33)
mbr_16 = tk.Checkbutton(otherFrame, text='').grid(row=3,column=34)
mbr_LD = tk.Button(otherFrame, text = "LD", fg = "green",padx=5,pady=5,relief=tk.RAISED).grid(row=3,column=35)

btn11= tk.Label(otherFrame, text = "IR", fg = "blue",padx=5,pady=5,relief=tk.RAISED)
btn11.grid(row=4,column=18)
ir_1 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=19)
ir_2 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=20)
ir_3 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=21)
ir_4 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=22)
ir_5 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=23)
ir_6 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=24)
ir_7 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=25)
ir_8 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=26)
ir_9 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=27)
ir_10 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=28)
ir_11 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=29)
ir_12 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=30)
ir_13 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=31)
ir_14 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=32)
ir_15 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=33)
ir_16 = tk.Checkbutton(otherFrame, text='').grid(row=4,column=34)

btn12= tk.Label(otherFrame, text = "MFR", fg = "blue",padx=5,pady=5,relief=tk.RAISED)
btn12.grid(row=5,column=30)
mfr_1 = tk.Checkbutton(otherFrame, text='').grid(row=5,column=31)
mfr_2 = tk.Checkbutton(otherFrame, text='').grid(row=5,column=32)
mfr_3 = tk.Checkbutton(otherFrame, text='').grid(row=5,column=33)
mfr_4 = tk.Checkbutton(otherFrame, text='').grid(row=5,column=34)

btn13= tk.Label(otherFrame, text = "Privileged", fg = "blue",padx=5,pady=5,relief=tk.RAISED)
btn13.grid(row=6,column=33)
priv_1 = tk.Checkbutton(otherFrame, text='').grid(row=6,column=34)

window.mainloop()


